title: Kaneka
author:
  name: Nathan Argetsinger
  email: 'nathan@haveli.io'
metadata:
    description: 'Kaneka is a powerfull open ecosystem and dynamic flexible construction system which is developed by Haveli.'